.TH groupwise-plugin "8" "17 Jul 2010" "groupwise-plugin" "Support Utilities Manual"
.SH NAME
groupwise-plugin \- GroupWise Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include GroupWise information. 
Informaiton is gathered for GroupWise Agents, Monitor, GWIA and WebAccess. Supportconfig saves the plugin output as plugin-groupwise.txt.
.SH FILES
.I /opt/supportconfig/plugins/groupwise
.RS
The groupwise plugin
.RE
.SH AUTHOR
Jason Record <jrecord@novell.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://code.google.com/p/supportutils-plugin-groupwise/issues/list
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
